### ISSUE TITLE
Practica Architec

### ISSUE THREAD

**Issue by ToniDepp** [SistemasTecTlaxiaco/actividad-3-practica-architect-ToniDepp#1]
[PRACARCH-EDUARDO-TOMAS-5US.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-ToniDepp/files/12553121/PRACARCH-EDUARDO-TOMAS-5US.pdf)

**Comment by Rufino07** [comment]
18%/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
